spring:
   profiles:
      active:
        - dev

info:
   app:
      name: appname  
   company:
      name: company22222
   
---
server:
  port: 8203

spring:
  profiles: dev
  application:
      name: microconfig-test-client

eureka:
 client:
  service-url:
    defaultZone: http://admin:enjoy@localhost:7001/eureka
---
server:
  port: 8102

spring:
  profiles: beta
  application:
      name: microconfig-test-client2

eureka:
 client:
  service-url:
    defaultZone: http://admin:enjoy@localhost:7001/eureka
