spring:
  profiles:
    active: 
    - dev
      

---
server:
  port: 7001
eureka:
  server:
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false
  client:
    service-url:
      defaultZone: http://admin:enjoy@localhost:7001/eureka
    fetch-registry: false
    register-with-eureka: false
  instance:
    hostname: localhost

spring:
  profiles: dev
  security:
    user:
      name: admin
      password: enjoy
  application:
    name: microcloud-config-eureka-client


---
server:
  port: 7002


eureka:
  server:
    eviction-interval-timer-in-ms: 1000
    enable-self-preservation: false
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://admin:enjoy@localhost:7002/eureka
  instance:
    hostname: localhost

spring:
  profiles: beta
  security:
    user:
      name: admin
      password: enjoy
  application:
    name: microcloud-config-eureka-client
